-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "defending" INTEGER NOT NULL DEFAULT 65,
ADD COLUMN     "pace" INTEGER NOT NULL DEFAULT 65,
ADD COLUMN     "passing" INTEGER NOT NULL DEFAULT 65,
ADD COLUMN     "rating" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN     "shooting" INTEGER NOT NULL DEFAULT 65;

